menu:
  Home: ../
  BlogTop: 
  Archives: archives

widgets:
- profile
- search
- tag

excerpt_link: Read More

twitter:
  username:
  show_replies: false
  tweet_count: 5

addthis:
  enable: true
  pubid:
  facebook: true
  twitter: true
  google: true
  pinterest: true

fancybox: true

google_analytics: UA-968682-24
rss:

comment_provider: 
